# Generated by Django 5.0.6 on 2025-05-31 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_name', models.CharField(max_length=50)),
                ('Admin_username', models.CharField(max_length=50)),
                ('Admin_ID', models.CharField(max_length=50)),
                ('Admin_email', models.EmailField(max_length=254)),
                ('Phno', models.IntegerField()),
                ('Password', models.CharField(max_length=50)),
                ('cmPassword', models.CharField(max_length=50)),
                ('DOB', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.IntegerField()),
            ],
            options={
                'db_table': 'Admin_signup',
            },
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=50)),
                ('Account_type', models.IntegerField()),
                ('Phno', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Inbox', models.CharField(max_length=350)),
            ],
            options={
                'db_table': 'complaint',
            },
        ),
        migrations.CreateModel(
            name='SignUp1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Phno', models.IntegerField()),
                ('Password', models.CharField(max_length=50)),
                ('cmPassword', models.CharField(max_length=50)),
                ('DOB', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.IntegerField()),
            ],
            options={
                'db_table': 'SignUp1',
            },
        ),
        migrations.CreateModel(
            name='trans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('IFSC', models.CharField(max_length=20)),
                ('accnumber', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('choose', models.CharField(max_length=50)),
                ('scnd_accnumber', models.IntegerField()),
            ],
            options={
                'db_table': 'trans',
            },
        ),
    ]
