# Generated by Django 5.0.6 on 2025-06-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techbank', '0002_open_delete_admin_signup_delete_complaint_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Open',
            new_name='OPENS',
        ),
    ]
