# Generated by Django 5.0.6 on 2025-06-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techbank', '0003_rename_open_opens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opens',
            old_name='choose',
            new_name='accountType',
        ),
        migrations.RenameField(
            model_name='opens',
            old_name='fullname',
            new_name='name',
        ),
    ]
