# Generated by Django 5.0.6 on 2025-06-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbank', '0004_rename_choose_opens_accounttype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opens',
            name='accountType',
        ),
        migrations.RemoveField(
            model_name='opens',
            name='name',
        ),
        migrations.AddField(
            model_name='opens',
            name='aadhar',
            field=models.CharField(default='000000000000', max_length=12),
        ),
        migrations.AddField(
            model_name='opens',
            name='account_type',
            field=models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opens',
            name='address',
            field=models.TextField(default='Not Provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opens',
            name='fullname',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opens',
            name='nation',
            field=models.CharField(default='Null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opens',
            name='pan',
            field=models.CharField(default='Null', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opens',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opens',
            name='photo',
            field=models.ImageField(default='Null', upload_to='photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opens',
            name='pincode',
            field=models.CharField(default='Null', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opens',
            name='state',
            field=models.CharField(default='Null', max_length=50),
            preserve_default=False,
        ),
    ]
