# Generated by Django 5.0.6 on 2025-06-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbank', '0005_remove_opens_accounttype_remove_opens_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('nation', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('aadhar', models.CharField(max_length=12)),
                ('pan', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('kyc_photo', models.ImageField(blank=True, null=True, upload_to='kyc_photos/')),
                ('choose', models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='OPENS',
        ),
    ]
