# Generated by Django 5.0.6 on 2025-06-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techbank', '0006_account_delete_opens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='user_acount_request',
        ),
    ]
