# Generated by Django 5.0.6 on 2025-06-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbank', '0008_alter_user_acount_request_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='userAcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('nation', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('aadhar', models.CharField(max_length=12, unique=True)),
                ('pan', models.CharField(max_length=10, unique=True)),
                ('photo', models.ImageField(upload_to='profile_photos/')),
                ('choose', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current')], max_length=30)),
                ('kyc_photo', models.ImageField(blank=True, null=True, upload_to='kyc_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
