# Generated by Django 5.0.6 on 2025-06-11 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbank', '0009_useracount'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('Home Loan', 'Home Loan'), ('Education Loan', 'Education Loan'), ('Personal Loan', 'Personal Loan')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_years', models.IntegerField()),
                ('account_no', models.CharField(max_length=20)),
                ('aadhar', models.CharField(max_length=12)),
                ('pan', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='loan_photos/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='techbank.useracount')),
            ],
        ),
    ]
