# Generated by Django 5.0.6 on 2025-06-21 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbank', '0010_loanapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('self-employed', 'Self-employed'), ('student', 'Student'), ('unemployed', 'Unemployed'), ('retired', 'Retired')], max_length=20)),
                ('annual_income', models.PositiveIntegerField()),
                ('card_type', models.CharField(choices=[('credit', 'Credit Card'), ('debit', 'Debit Card')], max_length=10)),
                ('id_proof', models.FileField(upload_to='id_proofs/')),
                ('address_proof', models.FileField(upload_to='address_proofs/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthInsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('individual', 'Individual Plan'), ('family', 'Family Plan'), ('senior', 'Senior Citizen Plan')], max_length=20, unique=True)),
                ('description', models.TextField()),
                ('coverage_amount', models.PositiveIntegerField(help_text='Amount in INR')),
                ('features', models.TextField(help_text='Comma-separated list of features')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LifeInsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('term', 'Term Insurance'), ('whole_life', 'Whole Life Policy'), ('ulip', 'Unit Linked Insurance Plan (ULIP)')], max_length=20, unique=True)),
                ('description', models.TextField()),
                ('features', models.TextField(help_text='Comma-separated features list')),
                ('coverage_amount', models.CharField(help_text="E.g., 'Up to ₹1 Crore'", max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('issue', models.TextField()),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Two-Wheeler', 'Two-Wheeler'), ('Commercial Vehicle', 'Commercial Vehicle')], max_length=30)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('registration', models.CharField(max_length=20)),
                ('registration_year', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('CNG', 'CNG')], max_length=20)),
                ('owner_name', models.CharField(max_length=100)),
                ('aadhar', models.CharField(max_length=12)),
                ('aadhar_photo', models.ImageField(upload_to='aadhar_photos/')),
                ('pan', models.CharField(max_length=10)),
                ('pan_photo', models.ImageField(upload_to='pan_photos/')),
                ('vehicle_photo', models.ImageField(upload_to='vehicle_photos/')),
                ('insurance_type', models.CharField(choices=[('Third-Party', 'Third-Party'), ('Comprehensive', 'Comprehensive'), ('Own Damage', 'Own Damage')], max_length=30)),
                ('duration', models.PositiveIntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='loanapplication',
            old_name='aadhar',
            new_name='aadhar_number',
        ),
        migrations.RenameField(
            model_name='loanapplication',
            old_name='account_no',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='loanapplication',
            old_name='applied_at',
            new_name='applied_on',
        ),
        migrations.RenameField(
            model_name='loanapplication',
            old_name='pan',
            new_name='pan_number',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='user',
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='amount',
            field=models.PositiveIntegerField(help_text='Loan amount in INR'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='duration_years',
            field=models.PositiveIntegerField(help_text='Loan duration in years'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_type',
            field=models.CharField(choices=[('home', 'Home Loan'), ('education', 'Education Loan'), ('personal', 'Personal Loan')], max_length=20),
        ),
        migrations.CreateModel(
            name='InsuranceQuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('requested_on', models.DateTimeField(auto_now_add=True)),
                ('selected_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techbank.healthinsuranceplan')),
            ],
        ),
        migrations.CreateModel(
            name='LifeInsuranceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('selected_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techbank.lifeinsuranceplan')),
            ],
        ),
    ]
