# Generated by Django 5.0.6 on 2025-06-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbank', '0011_cardapplication_healthinsuranceplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInsuranceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('dob', models.DateField()),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('id_type', models.CharField(choices=[('Aadhar', 'Aadhar'), ('PAN', 'PAN'), ('Passport', 'Passport'), ('Driving License', 'Driving License')], max_length=20)),
                ('id_number', models.CharField(max_length=30)),
                ('nominee_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('nominee_contact', models.CharField(max_length=15)),
                ('plan', models.CharField(choices=[('Individual Plan', 'Individual Plan'), ('Family Plan', 'Family Plan'), ('Senior Citizen Plan', 'Senior Citizen Plan')], max_length=25)),
                ('declaration', models.BooleanField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='insurancequoterequest',
            name='selected_plan',
        ),
        migrations.DeleteModel(
            name='HealthInsurancePlan',
        ),
        migrations.DeleteModel(
            name='InsuranceQuoteRequest',
        ),
    ]
