# Generated by Django 5.0.6 on 2025-06-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbank', '0012_healthinsuranceapplication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifeinsuranceapplication',
            name='selected_plan',
        ),
        migrations.DeleteModel(
            name='LoanApplication',
        ),
        migrations.RenameField(
            model_name='lifeinsuranceapplication',
            old_name='submitted_on',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='lifeinsuranceapplication',
            name='full_name',
        ),
        migrations.AddField(
            model_name='lifeinsuranceapplication',
            name='address',
            field=models.TextField(default='Not provided'),
        ),
        migrations.AddField(
            model_name='lifeinsuranceapplication',
            name='declaration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lifeinsuranceapplication',
            name='dob',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='lifeinsuranceapplication',
            name='fullname',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='lifeinsuranceapplication',
            name='gender',
            field=models.CharField(default='Not specified', max_length=10),
        ),
        migrations.AddField(
            model_name='lifeinsuranceapplication',
            name='id_number',
            field=models.CharField(default='0000-0000-0000', max_length=50),
        ),
        migrations.AddField(
            model_name='lifeinsuranceapplication',
            name='id_type',
            field=models.CharField(default='Aadhar Card', max_length=50),
        ),
        migrations.AddField(
            model_name='lifeinsuranceapplication',
            name='marital_status',
            field=models.CharField(default='Single', max_length=20),
        ),
        migrations.AddField(
            model_name='lifeinsuranceapplication',
            name='nominee_contact',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='lifeinsuranceapplication',
            name='nominee_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='lifeinsuranceapplication',
            name='plan',
            field=models.CharField(default='Term Plan', max_length=50),
        ),
        migrations.AddField(
            model_name='lifeinsuranceapplication',
            name='relationship',
            field=models.CharField(default='Not specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='lifeinsuranceapplication',
            name='email',
            field=models.EmailField(default='noemail@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='lifeinsuranceapplication',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.DeleteModel(
            name='LifeInsurancePlan',
        ),
    ]
