# Generated by Django 5.0.6 on 2025-06-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbank', '0013_remove_lifeinsuranceapplication_selected_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeinsuranceapplication',
            name='dob',
            field=models.DateField(default='dd/mm/yyyy'),
        ),
    ]
