# Generated by Django 5.0.6 on 2025-06-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbank', '0014_alter_lifeinsuranceapplication_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='trans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Unknown', max_length=100)),
                ('email', models.EmailField(default='unknown@example.com', max_length=254)),
                ('IFSC', models.CharField(default='UNKNOWN0000', max_length=20)),
                ('account_number', models.CharField(blank=True, default='0000000000', max_length=30, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateTimeField(default='timezone.now')),
            ],
        ),
        migrations.AddField(
            model_name='user_acount_request',
            name='password',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
