# Generated by Django 5.0.6 on 2025-06-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbank', '0015_trans_user_acount_request_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trans',
            name='date',
            field=models.DateTimeField(default='YYYY-MM-DD'),
        ),
    ]
