# Generated by Django 5.0.6 on 2025-06-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbank', '0016_alter_trans_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trans',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
