# Generated by Django 5.0.6 on 2025-06-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbank', '0017_alter_trans_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trans',
            old_name='full_name',
            new_name='fullname',
        ),
        migrations.AlterField(
            model_name='trans',
            name='account_number',
            field=models.CharField(default='0000000000', max_length=30),
        ),
    ]
