# Generated by Django 5.0.6 on 2025-06-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbank', '0018_rename_full_name_trans_fullname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('Home Loan', 'Home Loan'), ('Education Loan', 'Education Loan'), ('Personal Loan', 'Personal Loan')], max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField(help_text='In years')),
                ('account_no', models.CharField(max_length=20)),
                ('aadhar', models.CharField(max_length=12)),
                ('pan', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='loan_photos/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
